- id: 'heater_on_triggers'
  alias: "Heater: Turn on (3 triggers)"
  description: ""
  trigger:
    - platform: state
      entity_id:
        - schedule.heat
      to: "on"
    - platform: state
      entity_id:
        - zone.home
      from: "0"
    - platform: numeric_state
      entity_id: sensor.bom_canberra_temperature
      below: 15
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: climate.heater
          state: "off"
        - condition: state
          entity_id: schedule.heat
          state: "on"
        - condition: numeric_state
          entity_id: zone.home
          above: 0
        - condition: numeric_state
          entity_id: sensor.bom_canberra_temperature
          below: 15
  action:
    - service: climate.turn_on
      data: {}
      target:
        entity_id: climate.heater
  mode: single
- id: 'heater_off_triggers'
  alias: "Heater: Turn off (3 triggers)"
  description: ""
  trigger:
    - platform: state
      entity_id:
        - schedule.heat
      to: "off"
    - platform: numeric_state
      entity_id: sensor.bom_canberra_temperature
      above: 15
    - platform: state
      entity_id:
        - zone.home
      to: "0"
  condition:
    - condition: state
      entity_id: climate.heater
      state: heat
  action:
    - service: climate.turn_off
      data: {}
      target:
        entity_id: climate.heater
  mode: single



